# Generated by Django 3.0.6 on 2020-05-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='life',
            field=models.BooleanField(default=True),
        ),
    ]
