# Generated by Django 3.0.6 on 2020-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidate_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
